
# BIDS directory containing events.tsv files
BIDS_DIR: "/path/to/bids/dir"

# Directory containing example design.fsf file
FEAT_DIR: "/path/to/feat/dir"

# Directory containing output fmriprep directory
FMRIPREP_DIR: "/path/to/fmriprep/dir"

# Directory for confounder output report and figures
CONFOUNDER_DIR: "/path/to/output/dir"

# Location of participants.tsv file
participants_tsv: "/path/to/participants.tsv"

# Parameters for grabbing correct files from FMRIPREP_DIR
fmriprep_params:
    datatype: bold
    space: MNI152NLin2009cAsym
    desc: preproc
    task: taskname
    num_runs: 2

# Fixed parameters of bold scans
sequence_params:
    TR: 2

# Fixed task parameters
# Enter trial_names in order in which they appear in example design.fsf in FEAT_DIR
task_params:
    trial_names: ['trial1','trial2']

# Mask file for limiting search area (will throw error if mask file and func file are not in same space and spatial resolution).
# Optional.  If not specified, the "func/*_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz" file will be used.
MASK_FILE:

# Dictionary of confounds fron fMRIPrep confounds.tsv file.  Editable; keys are user-defined, values are column labels from confounds.tsv file.
CONFOUNDS:
  sixMotion: ['trans_x','trans_y','trans_z','rot_x','rot_y','rot_z']
  sixMotion-aCompCor00: ['trans_x','trans_y','trans_z','rot_x','rot_y','rot_z','a_comp_cor_00']
  sixMotion-tCompCor00: ['trans_x','trans_y','trans_z','rot_x','rot_y','rot_z','t_comp_cor_00']
  sixMotion-csf-wm: ['trans_x','trans_y','trans_z','rot_x','rot_y','rot_z','csf','white_matter']
  dvars: ['dvars']
  dvars-aCompCor00: ['dvars','a_comp_cor_00']
  dvars-tCompCor00: ['dvars','t_comp_cor_00']
  dvars-csf-wm: ['dvars','csf','white_matter']
  framewiseDisplacement: ['framewise_displacement']
  framewiseDisplacement-aCompCor00: ['framewise_displacement','a_comp_cor_00']
  framewiseDisplacement-tCompCor00: ['framewise_displacement','t_comp_cor_00']
  framewiseDisplacement-csf-wm: ['framewise_displacement','csf','white_matter']


# Specify a contrast vector (e.g., '1, -1, 0, 0').  Optional.  If not specified, the effects-of-interest F-contrast will be used.
CONTRAST:

